version: '3.0'

services:
  main:
    container_name: svt-nest-server
    image: drgnk/svt-nest-dev:latest
    env_file:
      - ./.docker.dev.env
    entrypoint: /entrypoint.sh

    ports:
      - 5003:5003
      - 9228:9228
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

  postgres:

    container_name: svt-postgres
    image: postgres:14
    env_file:
      - ./.docker.dev.env
    environment:
      PG_DATA: /var/lib/postgresql/svt-data
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/svt-data
    restart: always


volumes:
  pgdata:
      

