version: '3.0'

services:
  main:
    container_name: mhph-nest-server
    build:
      context: .
      dockerfile: ./src/Dockerfile.actions.dev
    env_file:
      - ./src/.docker.dev.env
    entrypoint: /entrypoint.sh

    ports:
      - 5001:5001
      - 9228:9228
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgress
    image: postgres:14
    env_file:
      - ./src/.docker.dev.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: