version: '3.0'

services:
  main:
    container_name: mhph-nest-server
    image: drgnk/mhph-nest-dev:latest
    env_file:
      - ./main/.docker.dev.env
    entrypoint: /entrypoint.sh

    ports:
      - 5001:5001
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
       # https://stackoverflow.com/a/52989931
    networks:
        - dockernet


  postgres:
    container_name: postgress
    image: postgres:14
    env_file:
      - ./main/.docker.dev.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
       # https://stackoverflow.com/a/52989931
    networks:
        - dockernet
   

volumes:
  pgdata:
  
# https://stackoverflow.com/a/52989931
networks:
  dockernet: