version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: ./src/Dockerfile.local.dev
    env_file:
      - ./src/.docker.dev.env
    entrypoint: /entrypoint.sh
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5003:5003
      - 9228:9228
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
    # https://stackoverflow.com/a/52989931
    networks:
        - dockernet

  postgres:
    container_name: postgress
    image: postgres:14
    env_file:
      - ./src/.docker.dev.env
    environment:
      PG_DATA: /var/lib/postgresql/svt-data
    ports:
      - 5434:5434
    volumes:
      - pgdata:/var/lib/postgresql/svt-data
    restart: always
    # https://stackoverflow.com/a/52989931
    networks:
        - dockernet

volumes:
  pgdata:

  # https://stackoverflow.com/a/52989931
networks:
    dockernet:
