version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: ./src/Dockerfile.local.dev
    env_file:
      - ./src/.docker.dev.env
    entrypoint: /entrypoint.sh
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5001:5001
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgress
    image: postgres:14
    env_file:
      - ./src/.docker.dev.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
