export enum RoleType {
  SYSTEM = 'SYSTEM',
  EXAMINED = 'EXAMINED',
  RESEARCHER = 'RESEARCHER',
}

export enum RoleValue {
  EXAMINED = 'EXAMINED',
  DOC_SPEC = 'DOC_SPEC',
  DOC_LOCAL = 'DOC_LOCAL',
  TRAINER_SPEC = 'TRAINER_SPEC',
  TRAINER_LOCAL = 'TRAINER_LOCAL',
  ADMIN = 'ADMIN',
  SUPER_USER = 'SUPER_USER',
}