FROM node:12.13-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

COPY ./src/entrypoint.sh /entrypoint.sh
RUN chmod u+x /entrypoint.sh

CMD [ "npm", "run", "start:dev"]
